name: Validate Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - v*.*.*

env:
  NODE_VERSION: 16

jobs: # list of things to do
  validate-pull-request:
    name: Validate the pull request # job name (unique id)
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
         node-version: ${{ env.NODE_VERSION }}
         registry-url: https://registry.npmjs.org/

      - name: Check out
        uses: actions/checkout@v3

      - name: do what has to be done
        run: |
          npm ci
          npm run build
          npm run test
